---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-database-deployment
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.java-demo-database: semver:~8.0

spec:
  replicas: 2
  template:
    spec:
      $setElementOrder/containers:
        - name: java-demo-database
      containers:
        - name: java-demo-database
          image: mysql:8.0.19
