apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Â BASES FOLDER ARE DIVIDED BY NAMESPACE

bases:
  - namespace
  - rbac
  - ingress

  - flux
  - istio
  - logging
  - monitoring
  # - logging

  - services
