---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-backend-deployment
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.java-demo-backend: glob:rc-*

spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: java-demo-backend
      containers:
        - name: java-demo-backend
          image: docker.io/jojoooo1/carros:1.1.0.RC-6dd3e69727479aee57e2961784b37086937bb697