---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-backend-deployment 
  labels:
    app: java-demo
    role: backend

spec:
  selector:
    matchLabels:
      app: java-demo
      role: backend

  # strategy:
  #   type: RollingUpdate # d.
  template:
    metadata:
      labels:
        app: java-demo
        role: backend

    spec:
      serviceAccountName: default # d. if you wanna set specific RBAC to the pod
      # restartPolicy: Always # d.
      containers:
        - name: java-demo-backend
          image: jojoooo1/carros:1.1.0.RC-0fbab77da628b0b3839017076b0b107ba14e772e
          # imagePullPolicy: Always # d.
          # env:
          #   - name: JAVA_TOOL_OPTIONS # used by distroless image
          #     value:
          ports:
            - name: container-port
              containerPort: 8080
          #
          # Liveness and Readiness
          # To use when restarting the app will recover it (heap, stack problems etc.)
          # livenessProbe:
          #   failureThreshold: 2 # d. 1
          #   periodSeconds: 15 # d. 10
          #   httpGet:
          #     port: 8080
          #     path: /actuator/health
          #
          # Indicates that the Pod has successfully initialized. 
          # No other probes are executed until this completes successfully.
          startupProbe:
            httpGet:
              path: /actuator/health
              port: container-port
            failureThreshold: 3
            periodSeconds: 25

          readinessProbe:
            periodSeconds: 10 # d.
            failureThreshold: 3 # d.
            httpGet:
              port: container-port
              path: /actuator/health
          # 
          # RESOURCES becarefull with container compatibility
          resources:
            requests:
              memory: "512Mi" # jib: -Xms512m
              cpu: "1"
            limits:
              memory: "1024Mi" # jib: -Xmx1024m
              cpu: "1"
