---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-backend-deployment 
  labels:
    app: java-demo
    role: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: java-demo
      role: backend

  template:
    metadata:
      labels:
        app: java-demo
        role: backend
        
    spec:
      serviceAccountName: default # d. if you wanna set specific RBAC to the pod
      # restartPolicy: Always # d.
      containers:
        - name: java-demo-backend
          image: docker.io/jojoooo1/carros
          # imagePullPolicy: Always # d.
          # env:
          #   - name: JAVA_TOOL_OPTIONS # used by distroless image
          #     value:
          ports:
            - name: container-port
              containerPort: 8080
          #
          # Liveness and Readiness
          # To use when restarting the app will recover it (heap, stack problems etc.)
          # livenessProbe:
          #   failureThreshold: 2 # d. 1
          #   periodSeconds: 15 # d. 10
          #   httpGet:
          #     port: 8080
          #     path: /actuator/health
          #
          # Indicates that the Pod has successfully initialized. 
          # No other probes are executed until this completes successfully.
          startupProbe:
            initialDelaySeconds: 60 # Becarefull with ressources, will have a direct effect on startup time
            httpGet:
              path: /actuator/health
              port: container-port
            failureThreshold: 4
            periodSeconds: 20 # d.

          readinessProbe:
            httpGet:
              port: container-port
              path: /actuator/health
            periodSeconds: 10 # d.
            failureThreshold: 4 # d.
          # TODO: Creates better one
          livenessProbe:
            httpGet:
              port: container-port
              path: /actuator/info
            periodSeconds: 10 # d.
            failureThreshold: 4 # d.
          # 
          # RESOURCES becarefull with container compatibility
          resources:
            requests:
              memory: "512Mi" # jib: -Xms256m # 94, 76.412 seconds 
              cpu: "0.5"
            limits:
              memory: "1024Mi" # jib: -Xmx512m
              cpu: "0.5"
