apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/service.yaml
  - database/deployment.yaml
  
  - backend/configmap.yaml
  - backend/service.yaml
  - backend/deployment.yaml