apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv

spec:
  # storageClassName: standard
  # Two way binding
  claimRef:
    name: alertmanager-pvc
    # needed => kustomize does not add it
    namespace: monitoring-system
  
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"