# INFO: To ensure two wy binding must ensure that both 1. *volumeName* and 2. *claimRef* are specified.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus-pv
spec:
  # claimRef:
  #   name: prometheus-pvc
  # # bug: kustomize does not template claimRef
  #   namespace: monitoring-system
  
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
