apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus-operator-prometheus

spec:
  # storageClassName: standard
  #Â Two way binding
  claimRef:
    name: prometheus-pvc

  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"
