apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../bases/istio

resources:
  - control-plane.yaml

# Delete default istio ns using $patch command
patchesStrategicMerge:
  - delete-default-ns.yaml # delete action can only be done using patchesStrategicMerge