apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

bases:
  - ../../../bases/istio

resources:
  - istio-gateway.yaml
  - istio-mtls-strict.yaml

patchesJson6902:
  # Replace flux operator arguments
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: 10m
          memory: 100Mi