apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #Â deleted namespace => will be defined in env
  - flux-account.yaml
  - flux-role.yaml
  - flux-secret.yaml
  - flux-deployment.yaml
