apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Sets namespace to flux-system i.e. flux operator will be installed in namespace "flux-system"
namespace: flux-system
# Gets flux operator default value
bases:
  - ../../bases/flux-operator/flux
  - ../../bases/flux-operator/memcached

# Creates namespace where flux-operator will live
resources:
  - namespace.yaml
# Update/Merge flux specific configuration for staging
patchesStrategicMerge:
  - flux-patch.yaml


  
