apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

#Â Gets flux operator default value
bases:
  - ../../bases/flux

patchesStrategicMerge:
  - flux-patch.yaml
  - helm-operator-patch.yaml
  
